import { Jost } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/NavBar";

const jost = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "Designo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jost.className} text-white`}>
        <NavBar />
        <main className={` m-auto`}>{children}</main>
      </body>
    </html>
  );
}
